/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ARangePicker: typeof import('ant-design-vue/es/date-picker/dayjs')['RangePicker']
    AResult: typeof import('ant-design-vue/es')['Result']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ChartPlaceholder: typeof import('./components/dashboard/ChartPlaceholder.vue')['default']
    DetectTaskActionCell: typeof import('./components/detect/DetectTaskActionCell.vue')['default']
    DetectTaskCreateBar: typeof import('./components/detect/DetectTaskCreateBar.vue')['default']
    DetectTaskQueryBar: typeof import('./components/detect/DetectTaskQueryBar.vue')['default']
    DetectTaskTable: typeof import('./components/detect/DetectTaskTable.vue')['default']
    ListEmptyGuide: typeof import('./components/common/ListEmptyGuide.vue')['default']
    ListQueryBar: typeof import('./components/common/ListQueryBar.vue')['default']
    ListTable: typeof import('./components/common/ListTable.vue')['default']
    PageLoading: typeof import('./components/common/PageLoading.vue')['default']
    ProjectActionCell: typeof import('./components/project/ProjectActionCell.vue')['default']
    ProjectCreateBar: typeof import('./components/project/ProjectCreateBar.vue')['default']
    ProjectDeleteModal: typeof import('./components/project/ProjectDeleteModal.vue')['default']
    ProjectFormModal: typeof import('./components/project/ProjectFormModal.vue')['default']
    ProjectQueryBar: typeof import('./components/project/ProjectQueryBar.vue')['default']
    ProjectTable: typeof import('./components/project/ProjectTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./components/dashboard/StatCard.vue')['default']
    TaskTypeText: typeof import('./components/detect/TaskTypeText.vue')['default']
  }
}
